language: erlang
script: "make && make verbose-test"
env: DB=couchdb
services:
    - couchdb
otp_release:
   - R15B03
   - R16B
   - R16B01
   - R16B02
   - R16B03
   - R16B03-1
   - 17.0
   - 17.1
   - 17.3
before_script:
  - curl -X PUT localhost:5984/couchbeam_testdb
  - curl -X PUT localhost:5984/couchbeam_testdb2
  - curl -X PUT localhost:5984/couchbeam_testdb3
notifications:
  irc:
    - "irc.freenode.org#couchdbkit"
